export const ImageTags = [
  { name: "Bedroom", key: 1, enumValue: "BEDROOM" },
  { name: "Bathroom", key: 2, enumValue: "BATHROOM" },
  { name: "Ensuite", key: 3, enumValue: "ENSUITE" },
  { name: "Lounge Room", key: 4, enumValue: "LOUNGE_ROOM" },
  { name: "Dining Room", key: 5, enumValue: "DINING_ROOM" },
  { name: "Front", key: 6, enumValue: "FRONT" },
  { name: "Front Garden", key: 7, enumValue: "FRONT_GARDEN" },
  { name: "Backyard", key: 8, enumValue: "BACKYARD" },
  { name: "Pool", key: 9, enumValue: "POOL" },
  { name: "Garage", key: 10, enumValue: "GARAGE" },
  { name: "Kitchen", key: 11, enumValue: "KITCHEN" },
  { name: "Laundry", key: 12, enumValue: "LAUNDRY" },
  { name: "Study", key: 13, enumValue: "STUDY" },
  { name: "Rumpus Room", key: 14, enumValue: "RUMPUS_ROOM" },
  { name: "Outdoor Area", key: 15, enumValue: "OUTDOOR_AREA" },
  { name: "Deck", key: 16, enumValue: "DECK" },
  { name: "Patio", key: 17, enumValue: "PATIO" },
];
